name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 772648344215.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t claims-api:latest .

      - name: Scan Docker image
        run: trivy image --exit-code 1 772648344215.dkr.ecr.us-east-1.amazonaws.com/claims-api:latest

      - name: Push Docker image to ECR
        run: docker push 772648344215.dkr.ecr.us-east-1.amazonaws.com/claims-api:latest

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/claims-api claims-api=772648344215.dkr.ecr.us-east-1.amazonaws.com/claims-api:latest -n claims-dev
